# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: teacher.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'teacher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rteacher.proto\x12\x07teacher\"8\n\x10SyncEmailRequest\x12\x11\n\told_email\x18\x01 \x01(\t\x12\x11\n\tnew_email\x18\x02 \x01(\t\"5\n\x11SyncEmailResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2T\n\x0eTeacherService\x12\x42\n\tSyncEmail\x12\x19.teacher.SyncEmailRequest\x1a\x1a.teacher.SyncEmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teacher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCEMAILREQUEST']._serialized_start=26
  _globals['_SYNCEMAILREQUEST']._serialized_end=82
  _globals['_SYNCEMAILRESPONSE']._serialized_start=84
  _globals['_SYNCEMAILRESPONSE']._serialized_end=137
  _globals['_TEACHERSERVICE']._serialized_start=139
  _globals['_TEACHERSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
